### ISSUE TITLE
Font increased incrementally

### ISSUE THREAD

**Issue by smaun** [alexmx/AMXFontAutoScale#3]
I have applied instance auto scaling on textView in viewDidLoad, when pop back to this screen after some navigation font gets increased, applying same steps result in further increment. I ve tried with UILabel, its also resulting same issue. Can you pls see into this?

**Comment by smaun** [comment]
Even this problem exist with your provided sample also, only we have to add some navigation i.e. push and then pop. This problem exist on devices other than reference screen means, if we are referring 4inch screen then iPhone 5 screen are good in back n forth but iPhone 6&6+ are performing these issues. It seems some calculations are over-performing every time view appears.

**Comment by alexmx** [comment]
@smaun Will take a look later today. Thanks for reporting this.

**Comment by alexmx** [comment]
@smaun Should be fixed in the latest release [1.0.4](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.0.4).

Can you please confirm that it is working fine for you?
