### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by ImanovTamerlan** [alexmx/AMXFontAutoScale#4]
After pod installing, application not starting

dyld: Library not loaded: @rpath/AMXFontAutoScale.framework/AMXFontAutoScale
  Referenced from: /Users/*/Library/Developer/CoreSimulator/Devices/85D96D3A-239A-4DE6-AA72-1B53E360D852/data/Containers/Bundle/Application/AA7EC658-AFD4-4FD1-BE18-30F5A23CDE22/*/*
  Reason: image not found

**Comment by alexmx** [comment]
@ImanovTamerlan can you please provide more information on your issue?

I've created a quick sample which pulls down the lib as pod and it works just fine: https://github.com/alexmx/AMXFontAutoScale/tree/master/examples/CocoaPodsIntegrationTest

Can you please check whether the framework is exported in your app product bundle? Like in image below:
![screen shot 2017-07-28 at 14 10 27](https://user-images.githubusercontent.com/1628901/28715005-b51b9670-739e-11e7-95e0-7b90c36498ed.png)

Please also check the **Runpath Search Paths** build setting as it might be overridden. 
However CocaPods should tell you this when you run `pod install`.

Cheers,
Alex.
