### ISSUE TITLE
Attribute text with diferent font

### ISSUE THREAD

**Issue by diegogmz** [alexmx/AMXFontAutoScale#5]
When I use your library, if I have more than one font in my attribute text, only the first font was loaded.

exemple of code, in this case, my text was only with font HoeflerTitling-Light.

`
let lb = UILabel(frame: CGRect(x: 0, y: 0, width: 160, height: 44)) lb.amx_autoScaleFont(forReferenceScreenSize: .size4Inch)
lb.amx_autoScaleEnabled = true
let alight = UIFont(name: "HoeflerTitling-Light", size: 22)!
let alightItalic = UIFont(name: "HoeflerTitling-LightItalic", size: 22)!
let myAttributeLight = [NSFontAttributeName: alight, NSForegroundColorAttributeName: UIColor(rgba: "#ed403d"), NSParagraphStyleAttributeName: paragraph]
 let attrString = NSAttributedString(string: "La Guía".localized(), attributes: myAttributeLight)
  myString.append(attrString)
            
 let myAttributeLightItalic = [NSFontAttributeName: alightItalic, NSForegroundColorAttributeName: UIColor(rgba: "#ed403d"), NSParagraphStyleAttributeName: paragraph]
let attrStringItalic = NSAttributedString(string: "del Prado".localized(), attributes: myAttributeLightItalic)
myString.append(attrStringItalic)
lb.attributedText = myString
`

**Comment by alexmx** [comment]
Hi @diegogmz 

This library doesn't handle the attributed text properties for **UILabel** and **UITextView**.
The font property of the label or text view is ignored when you set the attributed text property.

For this type of scenarios there is a closure handler which you can use to update the fonts manually when they should be updated:

```swift
lb.amx_fontSizeUpdateHandler = { originalSize, preferredSize, multiplier in
    // Update attributes with the new font sizes
}
```

Use `preferredSize` or `multiplier` to compute the new font and update the attributes of the string.

You need to update to the latest [version 1.1.0](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.1.0).

Cheers,
Alex.
