### ISSUE TITLE
Not working in viewDidAppear method

### ISSUE THREAD

**Issue by nihasmata** [alexmx/AMXFontAutoScale#9]
Hi ,Thank you for this helpful library. I have a problem updating my label which added to my ViewController using xib. 

```
 override func viewDidAppear() {
    super.viewDidAppear()
   myLabel.amx_autoScaleFont(forReferenceScreenSize: .size4Inch)
}

override func viewDidLayoutSubviews() {
 // Here i add my View which includes myLabel using xib
        let startView = UINib(nibName: "StartView", bundle: .main).instantiate(withOwner: self, options: nil).first as! UIView
}
```

**Comment by alexmx** [comment]
@nihasmata It's not gonna work in `viewDidAppear` as by this time it is too late to autoscale the text. 

As the method states, the view has already appeared on the screen so if you try to scale the label text at this time you gonna have a weird quick font size changing effect visible to the eye.

You can set the autoscaling for the label in the `didSet` observer of your outlet:
```swift
@IBOutlet weak var myLabel: UILabel! {
  didSet { myLabel.amx_autoScaleFont(forReferenceScreenSize: .size4Inch) }
}
```

Or you can set the reference screen size on the UILabel class for example:
```swift
UILabel.amx_referenceScreenSize = .size4Inch
```

And for your xib in Interface Builder enable autoscaling for your label like in this example: https://github.com/alexmx/AMXFontAutoScale#define-auto-scaling-for-multiple-instances
